//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carteles
    {
        public int Cartel_ID { get; set; }
        public int Pedido_ID { get; set; }
        public int Tamano_ID { get; set; }
        public int Tematica_ID { get; set; }
        public int Entregas_Tipo_ID { get; set; }
        public int Entregas_Lugar_ID { get; set; }
        public string Texto { get; set; }
        public string Colocacion_direccion { get; set; }
        public string Colocacion_barrio { get; set; }
        public string Colocacion_fecha { get; set; }
        public string Detalles { get; set; }
        public string CiudadInterior { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
