//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carteluxdbEntities : DbContext
    {
        public carteluxdbEntities()
            : base("name=carteluxdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entregas_lugar> entregas_lugar { get; set; }
        public virtual DbSet<entregas_tipo> entregas_tipo { get; set; }
        public virtual DbSet<tematicas> tematicas { get; set; }
        public virtual DbSet<tamanos> tamanos { get; set; }
        public virtual DbSet<carteles> carteles { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
    }
}
