//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarteluxDB : DbContext
    {
        public CarteluxDB()
            : base("name=CarteluxDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<formularios> formularios { get; set; }
        public virtual DbSet<lista_departamentos> lista_departamentos { get; set; }
        public virtual DbSet<lista_entregas_tipos> lista_entregas_tipos { get; set; }
        public virtual DbSet<lista_pedido_materiales> lista_pedido_materiales { get; set; }
        public virtual DbSet<lista_pedido_tamanos> lista_pedido_tamanos { get; set; }
        public virtual DbSet<lista_pedido_tematicas> lista_pedido_tematicas { get; set; }
        public virtual DbSet<lista_pedido_tipos> lista_pedido_tipos { get; set; }
        public virtual DbSet<pedido_disenos> pedido_disenos { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<pedido_entregas> pedido_entregas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
