//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int Cliente_ID { get; set; }
        public Nullable<int> Departamento_ID { get; set; }
        public string Telefono { get; set; }
        public string Nombre { get; set; }
        public string Barrio { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime Fecha_creado { get; set; }
        public System.DateTime Fecha_update { get; set; }
        public Nullable<int> NroDocumento { get; set; }
        public string Email { get; set; }
    }
}
