//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int Cliente_ID { get; set; }
        public string Telefono { get; set; }
        public string Nombre_completo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string Bario { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
