//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_emails
    {
        public int Config_emails_ID { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Descripcion { get; set; }
        public string Clave { get; set; }
        public bool EsEmisor { get; set; }
        public bool EsEntrega { get; set; }
        public bool EstaActivo { get; set; }
        public bool AlarmasOK { get; set; }
    }
}
