//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_alarmas
    {
        public int Config_alarmas_ID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Aviso_monto_ok { get; set; }
        public Nullable<int> Aviso_monto { get; set; }
        public bool Aviso_fecha_ok { get; set; }
        public Nullable<System.DateTime> Aviso_fecha { get; set; }
        public bool EstaActivo { get; set; }
    }
}
