//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_alarmas_ingresosMensual
    {
        public int Config_alarmas_ingresosMensual_ID { get; set; }
        public Nullable<int> Importe { get; set; }
        public bool EstaActivo { get; set; }
        public bool FlagMensual { get; set; }
    }
}
