//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_material_importes
    {
        public int Material_Importes_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Codigo { get; set; }
        public string Unidad { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
    }
}
