//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularios
    {
        public int Formulario_ID { get; set; }
        public int Prospecto_ID { get; set; }
        public int Codigo { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Nombre_completo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Telefono { get; set; }
        public int Motivo_ID { get; set; }
        public string Texto { get; set; }
        public string Comentarios { get; set; }
    }
}
