//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularios
    {
        public int Formulario_ID { get; set; }
        public int Cliente_ID { get; set; }
        public string Serie { get; set; }
        public string URL_short { get; set; }
        public string URL_completa { get; set; }
        public Nullable<int> Monto { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime Fecha_creado { get; set; }
        public System.DateTime Fecha_update { get; set; }
    }
}
