//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lista_componentes_volumen
    {
        public int componente_volumen_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Costo_volumen { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Codigo { get; set; }
        public Nullable<bool> isFondoColor { get; set; }
    }
}
