//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_disenos
    {
        public int Pedido_Diseno_ID { get; set; }
        public Nullable<int> Codigo_guia { get; set; }
        public string Texto { get; set; }
        public string Boceto_nombre { get; set; }
        public string Boceto_extension { get; set; }
        public string Boceto_PATH { get; set; }
    }
}
