//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int Pedido_ID { get; set; }
        public int Formulario_ID { get; set; }
        public int Pedido_Tipo_ID { get; set; }
        public int Pedido_Material_ID { get; set; }
        public int Pedido_Tamano_ID { get; set; }
        public int Pedido_Tematica_ID { get; set; }
        public int Pedido_Diseno_ID { get; set; }
        public int Pedido_Entrega_ID { get; set; }
        public int Cantidad { get; set; }
    }
}
