//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presupuestos_generados_productos
    {
        public int presupuesto_generado_producto_ID { get; set; }
        public int presupuesto_generado_ID { get; set; }
        public int Producto_ID { get; set; }
        public string Dato_fijo_txbNombre { get; set; }
        public Nullable<decimal> Dato_fijo_txbVolumen { get; set; }
        public Nullable<bool> Dato_fijo_chkFondoColor { get; set; }
        public Nullable<decimal> Dato_fijo_txbCostoUnitario { get; set; }
        public Nullable<decimal> Dato_fijo_txbPrecioUnitario { get; set; }
        public Nullable<bool> Dato_fijo_chkSugerido { get; set; }
        public Nullable<int> Dato_fijo_txbCantidadTotal { get; set; }
        public Nullable<decimal> Dato_fijo_txbSubotal1 { get; set; }
        public Nullable<int> Dato_fijo_txbDescuento { get; set; }
        public Nullable<decimal> Dato_fijo_txbSubotal2 { get; set; }
        public Nullable<decimal> Dato_fijo_txbRedondeo { get; set; }
        public Nullable<decimal> Dato_fijo_txbPrecioFinal { get; set; }
        public string Dato_fijo_txbComentarios { get; set; }
        public Nullable<decimal> Dato_fijo_txbCostoTotal { get; set; }
    }
}
