//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trading_ordenes
    {
        public int Orden_ID { get; set; }
        public Nullable<int> Operacion_ID { get; set; }
        public Nullable<int> Trade_ID { get; set; }
        public Nullable<int> Estado_ID { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
