//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartelux1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trading_lista_mercados
    {
        public int Mercado_ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Valor { get; set; }
    }
}
